version: '3.8'

services:
  php:
    build: .
    container_name: php_app
    volumes:
      - ./frontend:/var/www/html
    ports:
      - "8282:8282"
    working_dir: /var/www/html
    command: php -S 0.0.0.0:8282 -t /var/www/html
    networks:
      my_custom_network:
        ipv4_address: 172.18.0.10

  backend:
    build: .
    container_name: php_backend
    volumes:
      - ./backend:/var/www/html
    ports:
      - "8181:8181"  # Correction ici : même port à l'intérieur et à l’extérieur
    working_dir: /var/www/html
    command: php -S 0.0.0.0:8181 -t /var/www/html  # Démarre bien sur le port 8181
    networks:
      my_custom_network:
        ipv4_address: 172.18.0.11


networks:
  my_custom_network:
    driver: bridge
    ipam:
      config:
        - subnet: "172.18.0.0/16"
          gateway: "172.18.0.1"
