version: '3.8'

services:
  php:
    build: .
    container_name: php_app
    volumes:
      - ./php:/var/www/html
    ports:
      - "8080:8080"
    working_dir: /var/www/html
    command: php -S 0.0.0.0:8080 -t /var/www/html
    depends_on:
      - db
    networks:
      my_custom_network:
        ipv4_address: 172.18.0.10

  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: moduls
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql  # Charge le dump au démarrage
    networks:
      my_custom_network:
        ipv4_address: 172.18.0.11

  backup:
    image: mysql:8.0
    container_name: mysql_backup
    depends_on:
      - db
    volumes:
      - ./backups:/backup  # Monte un dossier au lieu d'un fichier
    entrypoint: ["sh", "-c", "while true; do mysqldump -hmysql_db -uuser -puserpassword moduls > /backup/dump.sql; sleep 360; done"]
    networks:
      my_custom_network:
        ipv4_address: 172.18.0.12


volumes:
  db_data:

networks:
  my_custom_network:
    driver: bridge
    ipam:
      config:
        - subnet: "172.18.0.0/16"
          gateway: "172.18.0.1"
