version: '3.8'

services:
  php:
    build: .
    container_name: php_app
    volumes:
      - ./php:/var/www/html
    ports:
      - "8080:8080"
    working_dir: /var/www/html
    command: php -S 0.0.0.0:8080 -t /var/www/html
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: moduls
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
